project.version: @project.version@

spring:
    jackson:
        mapper:
            DEFAULT_VIEW_INCLUSION: true
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        time-zone: GMT+2
    # Datababase configuration
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: false
                generate_statistics: false
    h2:
        console:
            enabled: true
            
# Configure keycloak realm
keycloak:
    auth-server-url: http://localhost:8180/auth
    realm: eoh
    resource: rest-api
    bearer-only: true
    ssl-required: external
    principal-attribute: preferred_username